### ISSUE TITLE
Can not run under python 3.7

### ISSUE THREAD

**Issue by beartell** [opentaps/opentaps_seas#53]
(opentaps) xentnex@mayapower:~/opentaps_seas$ python manage.py  --help
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/home/xentnex/opentaps_seas/opentaps/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/xentnex/opentaps_seas/opentaps/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/xentnex/opentaps_seas/opentaps/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/xentnex/opentaps_seas/opentaps/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/xentnex/opentaps_seas/opentaps/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/xentnex/opentaps_seas/opentaps/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xentnex/opentaps_seas/config/settings/local.py", line 18, in <module>
    from .base import *  # noqa
  File "/home/xentnex/opentaps_seas/config/settings/base.py", line 38, in <module>
    secrets = json.loads(f.read())
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 14 column 1 (char 415)

**Comment by sichen1234** [comment]
Did you try `source venv/bin/activate` from the opentaps_seas directory first?

**Comment by beartell** [comment]
It is working with python 3.8.
The problem may be with python version 3.9.
